CONFIG_AWS_REGION="eu-central-1"
CONFIG_AWS_PROFILE="personal-admin"
CONFIG_EKS_CLUSTER_NAME="kubeflow_cluster"

export AWS_REGION=$CONFIG_AWS_REGION
export AWS_PROFILE=$CONFIG_AWS_PROFILE
export CONFIG_EKS_CLUSTER_NAME=$CONFIG_EKS_CLUSTER_NAME