export CONFIG_EKS_CLUSTER_NAME="kubeflow_cluster"

echo "Used configuration:"
echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"
echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
echo "CONFIG_EKS_CLUSTER_NAME: $CONFIG_EKS_CLUSTER_NAME"